{"name": "Test CRUD operation Update(PUT).", "status": "broken", "statusDetails": {"message": "TypeError: put_requests() got an unexpected keyword argument 'data'", "trace": "self = <tests.test.integration.Integration TC1.TestCRUDPATCH object at 0x1057166c0>\nget_booking_id = 4452, create_token = 'a9e8c9d42a705db', booking_id = 4452\npayload = None\n\n    @allure.title(\"Test CRUD operation Update(PUT).\")\n    @allure.description(\n        \"Verify that Patch with the booking ID and Token is working.\")\n    def test_patch_update(self,get_booking_id, create_token, booking_id=None, payload=None,):\n        patch_url = APIConstants.url_patch_put_delete(booking_id=booking_id)\n        booking_id = get_booking_id\n        token = create_token\n>       response = put_requests(\n            url=patch_url,\n            headers=Util.common_header_put_delete_patch_cookie(self, token),\n            data=json.dumps(payload),\n            auth=None,\n            in_json=True\n        )\nE       TypeError: put_requests() got an unexpected keyword argument 'data'\n\nIntegration TC1.py:65: TypeError"}, "description": "Verify that Patch with the booking ID and Token is working.", "start": 1712729979467, "stop": 1712729979467, "uuid": "6c9c2ec8-26a5-45e3-8264-beafcb351a25", "historyId": "d3b7d48f4ce61b32126eae8f7f175fb9", "testCaseId": "d3b7d48f4ce61b32126eae8f7f175fb9", "fullName": "tests.test.integration.Integration TC1.TestCRUDPATCH#test_patch_update", "labels": [{"name": "parentSuite", "value": "tests.test.integration"}, {"name": "suite", "value": "Integration TC1"}, {"name": "subSuite", "value": "TestCRUDPATCH"}, {"name": "host", "value": "Davids-MBP"}, {"name": "thread", "value": "76005-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.integration.Integration TC1"}]}